// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZrivDKMIWR55s0M1mns-peyKj22f3B2U',
    appId: '1:678902716584:web:198cbaeb88e520aabd4a9d',
    messagingSenderId: '678902716584',
    projectId: 'nexplore-1bb9b',
    authDomain: 'nexplore-1bb9b.firebaseapp.com',
    storageBucket: 'nexplore-1bb9b.firebasestorage.app',
    measurementId: 'G-HCW5JTYY61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzsbb7EjbQP10qtk6hhz2rEUSvko2325A',
    appId: '1:678902716584:android:9d9413c466ab2f75bd4a9d',
    messagingSenderId: '678902716584',
    projectId: 'nexplore-1bb9b',
    storageBucket: 'nexplore-1bb9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx0oJTfphDJVumFN-eqE3yGQNHDmX7Uz8',
    appId: '1:678902716584:ios:e242d7eb8cb53a43bd4a9d',
    messagingSenderId: '678902716584',
    projectId: 'nexplore-1bb9b',
    storageBucket: 'nexplore-1bb9b.firebasestorage.app',
    iosBundleId: 'com.nexplore.mo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx0oJTfphDJVumFN-eqE3yGQNHDmX7Uz8',
    appId: '1:678902716584:ios:e242d7eb8cb53a43bd4a9d',
    messagingSenderId: '678902716584',
    projectId: 'nexplore-1bb9b',
    storageBucket: 'nexplore-1bb9b.firebasestorage.app',
    iosBundleId: 'com.nexplore.mo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZrivDKMIWR55s0M1mns-peyKj22f3B2U',
    appId: '1:678902716584:web:3d986db642ed4bafbd4a9d',
    messagingSenderId: '678902716584',
    projectId: 'nexplore-1bb9b',
    authDomain: 'nexplore-1bb9b.firebaseapp.com',
    storageBucket: 'nexplore-1bb9b.firebasestorage.app',
    measurementId: 'G-PNR00044WX',
  );
}
